#!/bin/bash
# SimpleStreams Setup Demo
#################################################################################
#IMAGE_SRC=https://images.maas.io/ephemeral-v3/daily/
IMAGE_SRC=https://cloud-images.ubuntu.com/releases/
IMAGE_DIR=/var/www/html/cloud-images/
KEYRING_FILE=/usr/share/keyrings/ubuntu-cloudimage-keyring.gpg

apt install -y ubuntu-cloudimage-keyring simplestreams nginx

[[ -d ${IMAGE_DIR} ]] || mkdir -p ${IMAGE_DIR}

sudo sstream-mirror --keyring=$KEYRING_FILE $IMAGE_SRC $IMAGE_DIR 'arch=amd64' 'release~(precise|trusty|xenial|bionic|cosmic)' --max=1 --progress

cat <<EOF > /etc/nginx/sites-enabled/default
location /maas {
  autoindex on;
}
EOF

sudo systemctl restart nginx.service
